language: php

php:
  - '7.4'

branches:
  only:
  - master

before_script:
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar install

script: ./vendor/bin/phpunit tests

notifications:
  email: false